name: "Pull Request Build"

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Define
        uses: ./.github/actions/define-environment
        with:
          environment: ${{ job.environment }}
